export const siteConfig = {
  name: "SP Power Engineers",
  shortName: "SPPE",
  description:
    "SP Power Engineers — EA Grade licensed electrical contractors in Chennai with 10+ years of expertise in electrical testing, commissioning, transformer services, solar & wind plant installation, switchyard T&C, and power quality analysis across India.",
  url: "https://www.sppowerengineers.com",
  keywords: [
    "electrical engineering",
    "power engineers",
    "electrical testing",
    "commissioning",
    "transformer services",
    "VCB service",
    "ACB service",
    "OLTC service",
    "solar plant installation",
    "solar plant testing and commissioning",
    "wind power installation",
    "wind power T&C",
    "switchyard installation",
    "switchyard testing",
    "data center commissioning",
    "data center installation",
    "thermal power plant T&C",
    "gas insulated substations",
    "industrial T&C",
    "mobility installation",
    "power quality analysis",
    "earth pit service",
    "power factor correction",
    "relay calibration",
    "thermography services",
    "meter calibration",
    "EA grade contractors",
    "ISO 9001 certified",
    "ISO 45001 certified",
    "electrical contractors Chennai",
    "Chennai",
    "India",
  ],
  contact: {
    phone: "+044 45864858",
    phone2: "(+91) 44 47706781",
    email: "info@sppowerengineers.com",
    address:
      "No: 5/9, 1st street, Arunachalam Nagar, Karambakkam, Porur, Chennai - 600116",
  },
  social: {
    linkedin: "#",
    instagram: "#",
    facebook: "#",
  },
  ogImage: "/images/og-image.jpg",
};

export type SiteConfig = typeof siteConfig;
